// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: channel.sql

package db

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (
    name
) VALUES (
    $1
) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateChannel(ctx context.Context, name string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, created_at, updated_at FROM channels
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetChannel(ctx context.Context, name string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
